apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: raw.pdns
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: raw.pdns.not-in-whitelist
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: raw.pdns.in-whitelist
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: domain.aggregate
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: graph.edge
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: domain.aggregate.full
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: graph.edge.full
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 3
  config:
    "retention.ms": "-1"
    "cleanup.policy": "compact"