// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/hitnslab/dnssecurity/pdnsdataloader/api/proto/pdns_data.proto

package com.hitnslab.dnssecurity.pdnsdataloader.api.proto;

public final class PDnsDataProto {

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\nAcom/hitnslab/dnssecurity/pdnsdataloade" +
            "r/api/proto/pdns_data.proto\0221com.hitnsla" +
            "b.dnssecurity.pdnsdataloader.api.proto\"r" +
            "\n\010PDnsData\022\022\n\nquery_time\030\001 \001(\003\022\016\n\006domain" +
            "\030\002 \001(\t\022\022\n\nquery_type\030\003 \001(\005\022\022\n\nreply_code" +
            "\030\004 \001(\005\022\032\n\022top_private_domain\030\005 \001(\tBG\n1co" +
            "m.hitnslab.dnssecurity.pdnsdataloader.ap" +
            "i.protoB\rPDnsDataProtoH\001\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            });
    internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_descriptor,
        new java.lang.String[]{"QueryTime", "Domain", "QueryType", "ReplyCode",
            "TopPrivateDomain",});
  }

  private PDnsDataProto() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface PDnsDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 query_time = 1;</code>
     *
     * @return The queryTime.
     */
    long getQueryTime();

    /**
     * <code>string domain = 2;</code>
     *
     * @return The domain.
     */
    java.lang.String getDomain();

    /**
     * <code>string domain = 2;</code>
     *
     * @return The bytes for domain.
     */
    com.google.protobuf.ByteString
    getDomainBytes();

    /**
     * <code>int32 query_type = 3;</code>
     *
     * @return The queryType.
     */
    int getQueryType();

    /**
     * <code>int32 reply_code = 4;</code>
     *
     * @return The replyCode.
     */
    int getReplyCode();

    /**
     * <code>string top_private_domain = 5;</code>
     *
     * @return The topPrivateDomain.
     */
    java.lang.String getTopPrivateDomain();

    /**
     * <code>string top_private_domain = 5;</code>
     *
     * @return The bytes for topPrivateDomain.
     */
    com.google.protobuf.ByteString
    getTopPrivateDomainBytes();
  }

  /**
   * Protobuf type {@code com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData}
   */
  public static final class PDnsData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData)
      PDnsDataOrBuilder {

    public static final int QUERY_TIME_FIELD_NUMBER = 1;
    public static final int DOMAIN_FIELD_NUMBER = 2;
    public static final int QUERY_TYPE_FIELD_NUMBER = 3;
    public static final int REPLY_CODE_FIELD_NUMBER = 4;
    public static final int TOP_PRIVATE_DOMAIN_FIELD_NUMBER = 5;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData)
    private static final com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<PDnsData>
        PARSER = new com.google.protobuf.AbstractParser<PDnsData>() {
      @java.lang.Override
      public PDnsData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PDnsData(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData();
    }

    private long queryTime_;
    private volatile java.lang.Object domain_;
    private int queryType_;
    private int replyCode_;
    private volatile java.lang.Object topPrivateDomain_;
    private byte memoizedIsInitialized = -1;

    // Use PDnsData.newBuilder() to construct.
    private PDnsData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private PDnsData() {
      domain_ = "";
      topPrivateDomain_ = "";
    }

    private PDnsData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              queryTime_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 24: {

              queryType_ = input.readInt32();
              break;
            }
            case 32: {

              replyCode_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              topPrivateDomain_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_descriptor;
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseDelimitedFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<PDnsData> parser() {
      return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PDnsData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData.class,
              com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData.Builder.class);
    }

    /**
     * <code>int64 query_time = 1;</code>
     *
     * @return The queryTime.
     */
    public long getQueryTime() {
      return queryTime_;
    }

    /**
     * <code>string domain = 2;</code>
     *
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }

    /**
     * <code>string domain = 2;</code>
     *
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
    getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>int32 query_type = 3;</code>
     *
     * @return The queryType.
     */
    public int getQueryType() {
      return queryType_;
    }

    /**
     * <code>int32 reply_code = 4;</code>
     *
     * @return The replyCode.
     */
    public int getReplyCode() {
      return replyCode_;
    }

    /**
     * <code>string top_private_domain = 5;</code>
     *
     * @return The topPrivateDomain.
     */
    public java.lang.String getTopPrivateDomain() {
      java.lang.Object ref = topPrivateDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topPrivateDomain_ = s;
        return s;
      }
    }

    /**
     * <code>string top_private_domain = 5;</code>
     *
     * @return The bytes for topPrivateDomain.
     */
    public com.google.protobuf.ByteString
    getTopPrivateDomainBytes() {
      java.lang.Object ref = topPrivateDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topPrivateDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (queryTime_ != 0L) {
        output.writeInt64(1, queryTime_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, domain_);
      }
      if (queryType_ != 0) {
        output.writeInt32(3, queryType_);
      }
      if (replyCode_ != 0) {
        output.writeInt32(4, replyCode_);
      }
      if (!getTopPrivateDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, topPrivateDomain_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (queryTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, queryTime_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, domain_);
      }
      if (queryType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, queryType_);
      }
      if (replyCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, replyCode_);
      }
      if (!getTopPrivateDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, topPrivateDomain_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData)) {
        return super.equals(obj);
      }
      com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData other = (com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData) obj;

      if (getQueryTime()
          != other.getQueryTime()) {
        return false;
      }
      if (!getDomain()
          .equals(other.getDomain())) {
        return false;
      }
      if (getQueryType()
          != other.getQueryType()) {
        return false;
      }
      if (getReplyCode()
          != other.getReplyCode()) {
        return false;
      }
      if (!getTopPrivateDomain()
          .equals(other.getTopPrivateDomain())) {
        return false;
      }
      if (!unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueryTime());
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (37 * hash) + QUERY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getQueryType();
      hash = (37 * hash) + REPLY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getReplyCode();
      hash = (37 * hash) + TOP_PRIVATE_DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getTopPrivateDomain().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PDnsData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData)
        com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsDataOrBuilder {

      private long queryTime_;
      private java.lang.Object domain_ = "";
      private int queryType_;
      private int replyCode_;
      private java.lang.Object topPrivateDomain_ = "";

      // Construct using com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData.class,
                com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        queryTime_ = 0L;

        domain_ = "";

        queryType_ = 0;

        replyCode_ = 0;

        topPrivateDomain_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.internal_static_com_hitnslab_dnssecurity_pdnsdataloader_api_proto_PDnsData_descriptor;
      }

      @java.lang.Override
      public com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData getDefaultInstanceForType() {
        return com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData build() {
        com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData buildPartial() {
        com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData result = new com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData(
            this);
        result.queryTime_ = queryTime_;
        result.domain_ = domain_;
        result.queryType_ = queryType_;
        result.replyCode_ = replyCode_;
        result.topPrivateDomain_ = topPrivateDomain_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData) {
          return mergeFrom(
              (com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData other) {
        if (other == com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData
            .getDefaultInstance()) {
          return this;
        }
        if (other.getQueryTime() != 0L) {
          setQueryTime(other.getQueryTime());
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (other.getQueryType() != 0) {
          setQueryType(other.getQueryType());
        }
        if (other.getReplyCode() != 0) {
          setReplyCode(other.getReplyCode());
        }
        if (!other.getTopPrivateDomain().isEmpty()) {
          topPrivateDomain_ = other.topPrivateDomain_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsDataProto.PDnsData) e
              .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>int64 query_time = 1;</code>
       *
       * @return The queryTime.
       */
      public long getQueryTime() {
        return queryTime_;
      }

      /**
       * <code>int64 query_time = 1;</code>
       *
       * @param value The queryTime to set.
       * @return This builder for chaining.
       */
      public Builder setQueryTime(long value) {

        queryTime_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int64 query_time = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearQueryTime() {

        queryTime_ = 0L;
        onChanged();
        return this;
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @return The domain.
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @param value The domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        domain_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @return The bytes for domain.
       */
      public com.google.protobuf.ByteString
      getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @param value The bytes for domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        domain_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDomain() {

        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }

      /**
       * <code>int32 query_type = 3;</code>
       *
       * @return The queryType.
       */
      public int getQueryType() {
        return queryType_;
      }

      /**
       * <code>int32 query_type = 3;</code>
       *
       * @param value The queryType to set.
       * @return This builder for chaining.
       */
      public Builder setQueryType(int value) {

        queryType_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 query_type = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearQueryType() {

        queryType_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int32 reply_code = 4;</code>
       *
       * @return The replyCode.
       */
      public int getReplyCode() {
        return replyCode_;
      }

      /**
       * <code>int32 reply_code = 4;</code>
       *
       * @param value The replyCode to set.
       * @return This builder for chaining.
       */
      public Builder setReplyCode(int value) {

        replyCode_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 reply_code = 4;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearReplyCode() {

        replyCode_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>string top_private_domain = 5;</code>
       *
       * @return The topPrivateDomain.
       */
      public java.lang.String getTopPrivateDomain() {
        java.lang.Object ref = topPrivateDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topPrivateDomain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string top_private_domain = 5;</code>
       *
       * @param value The topPrivateDomain to set.
       * @return This builder for chaining.
       */
      public Builder setTopPrivateDomain(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        topPrivateDomain_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string top_private_domain = 5;</code>
       *
       * @return The bytes for topPrivateDomain.
       */
      public com.google.protobuf.ByteString
      getTopPrivateDomainBytes() {
        java.lang.Object ref = topPrivateDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topPrivateDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string top_private_domain = 5;</code>
       *
       * @param value The bytes for topPrivateDomain to set.
       * @return This builder for chaining.
       */
      public Builder setTopPrivateDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        topPrivateDomain_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string top_private_domain = 5;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearTopPrivateDomain() {

        topPrivateDomain_ = getDefaultInstance().getTopPrivateDomain();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.hitnslab.dnssecurity.pdnsdataloader.api.proto.PDnsData)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
