apiVersion: v1
kind: Service
metadata:
  name: stream-graph
  namespace: default
  labels:
    app.kubernetes.io/name: stream-graph
    app.kubernetes.io/part-of: deeparcher
    app.kubernetes.io/component: stream
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: jmx
      port: 9999
      protocol: TCP
  selector:
    app.kubernetes.io/name: stream-graph
    app.kubernetes.io/part-of: deeparcher
    app.kubernetes.io/component: stream