spring:
  task:
    execution:
      pool:
        core-size: 8
  kafka:
    bootstrap-servers:
      - kafka-kafka-bootstrap:9092
    ssl:
      protocol: TLSv1.2
      key-store-type: PKCS12
      key-store-location: kafka-user-test.p12
      key-store-password: # Inject it via env $SPRING_KAFKA_SSL_KEY_STORE_PASSWORD
      #      key-password: $ Not needed
      trust-store-type: PKCS12
      trust-store-location: kafka-user-test.p12
      trust-store-password: # Inject it via env $SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.hitnslab.dnssecurity.pdnsdataloader.serdes.PDnsSerializer
      acks: 1
      compression-type: gzip
      client-id: PDNS_DATA_LOADER
      batch-size: 1000000
      properties:
        linger.ms: 10000
    template:
      default-topic: test.raw.pdns
    properties:
      security.protocol: SSL
  #      ssl.endpoint.identification.algorithm: ""
  batch:
    initialize-schema: always
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      connection-timeout: 300000
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 1800000
      maximum-pool-size: 32
      minimum-idle: 2
      pool-name: spring-batch-db-pool
app:
  job:
    slave-step:
      #      transaction:
      #        manager: org.springframework.kafka.transaction.KafkaTransactionManager
      chunk-size: 10000
      retry-limit: 10
      item-reader:
        field-set-mapper: com.hitnslab.dnssecurity.pdnsdataloader.parsing.HITPDNSLogFieldSetMapper
      item-writer:
        name: kafka
# management:
#   health:
#     db:
#       enabled: false
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
com:
  sun:
    management:
      jmxremote:
        port: 56789
        authenticate: false
        ssl: false
