spring:
  task:
    execution:
      pool:
        core-size: 12
  kafka:
    producer:
      bootstrap-servers:
        - kafka-headless:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.hitnslab.dnssecurity.pdnsdataloader.serdes.PDnsSerializer
      acks: 1
      compression-type: gzip
      client-id: PDNS_DATA_LOADER
    #      transaction-id-prefix: PDNS_DATA_LOADER
    template:
      default-topic: test.raw.pdns
  batch:
    initialize-schema: always
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      connection-timeout: 300000
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 1800000
      maximum-pool-size: 32
      minimum-idle: 2
      pool-name: spring-batch-db-pool
app:
  job:
    slave-step:
      #      transaction:
      #        manager: org.springframework.kafka.transaction.KafkaTransactionManager
      chunk-size: 120000
      retry-limit: 10
      item-reader:
        field-set-mapper: com.hitnslab.dnssecurity.pdnsdataloader.parsing.HITPDNSLogFieldSetMapper
      item-writer:
        name: kafka
# management:
#   health:
#     db:
#       enabled: false
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
com:
  sun:
    management:
      jmxremote:
        port: 56789
        authenticate: false
        ssl: false
