spring:
  batch:
    initialize-schema: always
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      connection-timeout: 300000
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 1800000
      maximum-pool-size: 48
      minimum-idle: 6
      pool-name: spring-batch-db-pool
app:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      connection-timeout: 300000
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 1800000
      maximum-pool-size: 48
      minimum-idle: 6
      pool-name: spring-batch-db-pool
# management:
#   health:
#     db:
#       enabled: false
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
com:
  sun:
    management:
      jmxremote:
        port: 56789
        authenticate: false
        ssl: false
