spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
app:
  datasource:
    url: jdbc:omnisci:nistdev0:6274:omnisci
    username: admin
    password: HITnsLAB-admin!
    driver-class-name: com.omnisci.jdbc.OmniSciDriver