spring:
  batch:
    initialize-schema: always
  datasource:
    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    #    username: sa
    #    password: sa
    url: jdbc:mariadb://nistdev0:3306/springbatch?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: springbatch
    password: HITnsLAB-springbatch!
    hikari:
      connection-timeout: 300000
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 600000
      maximum-pool-size: 512
      minimum-idle: 12
      pool-name: spring-batch-db-pool
app:
  datasource:
    url: jdbc:omnisci:nistdev0:6274:omnisci
    username: admin
    password: HITnsLAB-admin!
    driver-class-name: com.omnisci.jdbc.OmniSciDriver
    hikari:
      connection-timeout: 3600000
      idle-timeout: 600000
      validation-timeout: 10000
      max-lifetime: 1800000
      maximum-pool-size: 96
      minimum-idle: 6
      pool-name: omnisci-db-pool
# management:
#   health:
#     db:
#       enabled: false
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
com:
  sun:
    management:
      jmxremote:
        port: 56789
        authenticate: false
        ssl: false
