apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-0
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/volumes/kafka
  claimRef:
    namespace: default
    name: data-kafka-kafka-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node30
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-1
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/volumes/kafka
  claimRef:
    namespace: default
    name: data-kafka-kafka-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node31
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-2
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/volumes/kafka
  claimRef:
    namespace: default
    name: data-kafka-kafka-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node32
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-3
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/volumes/kafka
  claimRef:
    namespace: default
    name: data-kafka-kafka-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-gpu-node0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-4
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/volumes/kafka
  claimRef:
    namespace: default
    name: data-kafka-kafka-4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node34
