sh.shardCollection("data.malicious_domains_history", {"fqdn": "hashed"}, false)
sh.shardCollection("data.whois_details", {"fqdn": "hashed"}, false)
sh.shardCollection("data.legal_domains", {"fqdn": "hashed"}, false)
sh.shardCollection("data.passive_dns_logs", {"fqdn": "hashed"}, false)
sh.shardCollection("data.geoinfo_history", {"fqdn": "hashed"}, false)
sh.shardCollection("data.certificates_history", {"fqdn": "hashed"}, false)
sh.shardCollection("analysis.domain_attributes", {"fqdn": "hashed"}, false)
sh.shardCollection("data.active_dns_history", {"domain": "hashed"}, false)
