kind: ConfigMap
apiVersion: v1
metadata:
  name: stream-whitelist-filter
  namespace: default
  labels:
    app.kubernetes.io/name: stream-whitelist-filter
    app.kubernetes.io/part-of: deeparcher
    app.kubernetes.io/component: stream
data:
  application.yml: |-
    spring:
      autoconfigure:
        exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      kafka:
        bootstrap-servers:
          - kafka-kafka-bootstrap:9093
        ssl:
          protocol: TLSv1.3
          key-store-type: PKCS12
          key-store-location: file:///var/run/secrets/java.io/keystores/user.p12
          key-store-password: # Inject it via env $SPRING_KAFKA_SSL_KEY_STORE_PASSWORD
          trust-store-type: JKS
          trust-store-location: file:///var/run/secrets/java.io/truststores/ca.jks
          trust-store-password: # Inject it via env $SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD
        properties:
          security.protocol: SSL
          ssl.enabled.protocols: TLSv1.3
          # ssl.endpoint.identification.algorithm: ""
          metadata.max.age.ms: 60000
          receive.buffer.bytes: 2097152
          delivery.timeout.ms: 1800000
        streams:
          application-id: stream-whitelist-filter
          state-dir: /tmp/kafka-stream
          replication-factor: 2
          auto-startup: true
          properties:
            topology.optimization: all
            num.stream.threads: 2
            consumer.max-poll-records: 5000000
            consumer.fetch-max-wait: 2000
            consumer.auto-offset-reset: earliest

    app:
      whitelist-filter:
        enabled: true
        prefilters:
          - field: domain
            pattern: "hitwh\\.edu\\.cn$"
            allow: false
        whitelists:
          - type: file
            path: file:///data/whitelist.txt
          - type: regex
            path: "\\.(edu|gov)(\\.[a-z]{2})?$"
        input:
          type: topic
          path: raw.pdns
        output:
          match:
            - type: topic
              path: raw.pdns.in-whitelist
              options:
                unique: false
          miss:
            - type: topic
              path: raw.pdns.not-in-whitelist
              options:
                unique: false
