apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-user-admin
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: cluster
        operation: All
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: All
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All