apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-user-test
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: test.
          patternType: prefix
        operation: All
      - resource:
          type: group
          name: test.
          patternType: prefix
        operation: All
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Describe
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: DescribeConfigs

      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: Read
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: DescribeConfigs

      - resource:
          type: transactionalId
          name: test.
          patternType: prefix
        operation: All
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: Read
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: Describe
