// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/hitnslab/dnssecurity/deeparcher/api/proto/domain_ip_assoc_detail.proto

package com.hitnslab.dnssecurity.deeparcher.api.proto;

public final class DomainIPAssocDetailProto {

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\nJcom/hitnslab/dnssecurity/deeparcher/ap" +
            "i/proto/domain_ip_assoc_detail.proto\022-co" +
            "m.hitnslab.dnssecurity.deeparcher.api.pr" +
            "oto\"[\n\023DomainIPAssocDetail\022\014\n\004fqdn\030\001 \001(\t" +
            "\022\016\n\006domain\030\002 \001(\t\022\022\n\nipv4_addrs\030\007 \001(\014\022\022\n\n"
            +
            "ipv6_addrs\030\010 \001(\014BN\n-com.hitnslab.dnssecu" +
            "rity.deeparcher.api.protoB\030DomainIPAssoc" +
            "DetailProtoH\001\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            });
    internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_descriptor,
        new java.lang.String[]{"Fqdn", "Domain", "Ipv4Addrs", "Ipv6Addrs",});
  }

  private DomainIPAssocDetailProto() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface DomainIPAssocDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fqdn = 1;</code>
     *
     * @return The fqdn.
     */
    java.lang.String getFqdn();

    /**
     * <code>string fqdn = 1;</code>
     *
     * @return The bytes for fqdn.
     */
    com.google.protobuf.ByteString
    getFqdnBytes();

    /**
     * <code>string domain = 2;</code>
     *
     * @return The domain.
     */
    java.lang.String getDomain();

    /**
     * <code>string domain = 2;</code>
     *
     * @return The bytes for domain.
     */
    com.google.protobuf.ByteString
    getDomainBytes();

    /**
     * <code>bytes ipv4_addrs = 7;</code>
     *
     * @return The ipv4Addrs.
     */
    com.google.protobuf.ByteString getIpv4Addrs();

    /**
     * <code>bytes ipv6_addrs = 8;</code>
     *
     * @return The ipv6Addrs.
     */
    com.google.protobuf.ByteString getIpv6Addrs();
  }

  /**
   * Protobuf type {@code com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail}
   */
  public static final class DomainIPAssocDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail)
      DomainIPAssocDetailOrBuilder {

    public static final int FQDN_FIELD_NUMBER = 1;
    public static final int DOMAIN_FIELD_NUMBER = 2;
    public static final int IPV4_ADDRS_FIELD_NUMBER = 7;
    public static final int IPV6_ADDRS_FIELD_NUMBER = 8;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail)
    private static final com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<DomainIPAssocDetail>
        PARSER = new com.google.protobuf.AbstractParser<DomainIPAssocDetail>() {
      @java.lang.Override
      public DomainIPAssocDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DomainIPAssocDetail(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail();
    }

    private volatile java.lang.Object fqdn_;
    private volatile java.lang.Object domain_;
    private com.google.protobuf.ByteString ipv4Addrs_;
    private com.google.protobuf.ByteString ipv6Addrs_;
    private byte memoizedIsInitialized = -1;

    // Use DomainIPAssocDetail.newBuilder() to construct.
    private DomainIPAssocDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private DomainIPAssocDetail() {
      fqdn_ = "";
      domain_ = "";
      ipv4Addrs_ = com.google.protobuf.ByteString.EMPTY;
      ipv6Addrs_ = com.google.protobuf.ByteString.EMPTY;
    }

    private DomainIPAssocDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fqdn_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 58: {

              ipv4Addrs_ = input.readBytes();
              break;
            }
            case 66: {

              ipv6Addrs_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_descriptor;
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseDelimitedFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<DomainIPAssocDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DomainIPAssocDetail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail.class,
              com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail.Builder.class);
    }

    /**
     * <code>string fqdn = 1;</code>
     *
     * @return The fqdn.
     */
    public java.lang.String getFqdn() {
      java.lang.Object ref = fqdn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fqdn_ = s;
        return s;
      }
    }

    /**
     * <code>string fqdn = 1;</code>
     *
     * @return The bytes for fqdn.
     */
    public com.google.protobuf.ByteString
    getFqdnBytes() {
      java.lang.Object ref = fqdn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fqdn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string domain = 2;</code>
     *
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }

    /**
     * <code>string domain = 2;</code>
     *
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
    getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>bytes ipv4_addrs = 7;</code>
     *
     * @return The ipv4Addrs.
     */
    public com.google.protobuf.ByteString getIpv4Addrs() {
      return ipv4Addrs_;
    }

    /**
     * <code>bytes ipv6_addrs = 8;</code>
     *
     * @return The ipv6Addrs.
     */
    public com.google.protobuf.ByteString getIpv6Addrs() {
      return ipv6Addrs_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!getFqdnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fqdn_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, domain_);
      }
      if (!ipv4Addrs_.isEmpty()) {
        output.writeBytes(7, ipv4Addrs_);
      }
      if (!ipv6Addrs_.isEmpty()) {
        output.writeBytes(8, ipv6Addrs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (!getFqdnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fqdn_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, domain_);
      }
      if (!ipv4Addrs_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, ipv4Addrs_);
      }
      if (!ipv6Addrs_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(8, ipv6Addrs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail)) {
        return super.equals(obj);
      }
      com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail other = (com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail) obj;

      if (!getFqdn()
          .equals(other.getFqdn())) {
        return false;
      }
      if (!getDomain()
          .equals(other.getDomain())) {
        return false;
      }
      if (!getIpv4Addrs()
          .equals(other.getIpv4Addrs())) {
        return false;
      }
      if (!getIpv6Addrs()
          .equals(other.getIpv6Addrs())) {
        return false;
      }
      if (!unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FQDN_FIELD_NUMBER;
      hash = (53 * hash) + getFqdn().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (37 * hash) + IPV4_ADDRS_FIELD_NUMBER;
      hash = (53 * hash) + getIpv4Addrs().hashCode();
      hash = (37 * hash) + IPV6_ADDRS_FIELD_NUMBER;
      hash = (53 * hash) + getIpv6Addrs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DomainIPAssocDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail)
        com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetailOrBuilder {

      private java.lang.Object fqdn_ = "";
      private java.lang.Object domain_ = "";
      private com.google.protobuf.ByteString ipv4Addrs_ = com.google.protobuf.ByteString.EMPTY;
      private com.google.protobuf.ByteString ipv6Addrs_ = com.google.protobuf.ByteString.EMPTY;

      // Construct using com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail.class,
                com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        fqdn_ = "";

        domain_ = "";

        ipv4Addrs_ = com.google.protobuf.ByteString.EMPTY;

        ipv6Addrs_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.internal_static_com_hitnslab_dnssecurity_deeparcher_api_proto_DomainIPAssocDetail_descriptor;
      }

      @java.lang.Override
      public com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail getDefaultInstanceForType() {
        return com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail build() {
        com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail buildPartial() {
        com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail result = new com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail(
            this);
        result.fqdn_ = fqdn_;
        result.domain_ = domain_;
        result.ipv4Addrs_ = ipv4Addrs_;
        result.ipv6Addrs_ = ipv6Addrs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail) {
          return mergeFrom(
              (com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail other) {
        if (other
            == com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail
            .getDefaultInstance()) {
          return this;
        }
        if (!other.getFqdn().isEmpty()) {
          fqdn_ = other.fqdn_;
          onChanged();
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (other.getIpv4Addrs() != com.google.protobuf.ByteString.EMPTY) {
          setIpv4Addrs(other.getIpv4Addrs());
        }
        if (other.getIpv6Addrs() != com.google.protobuf.ByteString.EMPTY) {
          setIpv6Addrs(other.getIpv6Addrs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetailProto.DomainIPAssocDetail) e
              .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>string fqdn = 1;</code>
       *
       * @return The fqdn.
       */
      public java.lang.String getFqdn() {
        java.lang.Object ref = fqdn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fqdn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string fqdn = 1;</code>
       *
       * @param value The fqdn to set.
       * @return This builder for chaining.
       */
      public Builder setFqdn(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        fqdn_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string fqdn = 1;</code>
       *
       * @return The bytes for fqdn.
       */
      public com.google.protobuf.ByteString
      getFqdnBytes() {
        java.lang.Object ref = fqdn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fqdn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string fqdn = 1;</code>
       *
       * @param value The bytes for fqdn to set.
       * @return This builder for chaining.
       */
      public Builder setFqdnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        fqdn_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string fqdn = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearFqdn() {

        fqdn_ = getDefaultInstance().getFqdn();
        onChanged();
        return this;
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @return The domain.
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @param value The domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        domain_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @return The bytes for domain.
       */
      public com.google.protobuf.ByteString
      getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @param value The bytes for domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        domain_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string domain = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDomain() {

        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }

      /**
       * <code>bytes ipv4_addrs = 7;</code>
       *
       * @return The ipv4Addrs.
       */
      public com.google.protobuf.ByteString getIpv4Addrs() {
        return ipv4Addrs_;
      }

      /**
       * <code>bytes ipv4_addrs = 7;</code>
       *
       * @param value The ipv4Addrs to set.
       * @return This builder for chaining.
       */
      public Builder setIpv4Addrs(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        ipv4Addrs_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes ipv4_addrs = 7;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearIpv4Addrs() {

        ipv4Addrs_ = getDefaultInstance().getIpv4Addrs();
        onChanged();
        return this;
      }

      /**
       * <code>bytes ipv6_addrs = 8;</code>
       *
       * @return The ipv6Addrs.
       */
      public com.google.protobuf.ByteString getIpv6Addrs() {
        return ipv6Addrs_;
      }

      /**
       * <code>bytes ipv6_addrs = 8;</code>
       *
       * @param value The ipv6Addrs to set.
       * @return This builder for chaining.
       */
      public Builder setIpv6Addrs(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        ipv6Addrs_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes ipv6_addrs = 8;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearIpv6Addrs() {

        ipv6Addrs_ = getDefaultInstance().getIpv6Addrs();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.hitnslab.dnssecurity.deeparcher.api.proto.DomainIPAssocDetail)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
