FROM dockerhub.hitnslab.com/library/openjdk:15-jdk-slim

LABEL maintainer="Yanzhe Lee"

WORKDIR /app

COPY target/*.jar ./app.jar

ENV JVM_OPTS "-server -Xmx4g -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xlog:gc*:gc.log"

ENV EXTRA_OPTS ""

ENV JOB_PARAMETERS ""

CMD java $JVM_OPTS $EXTRA_OPTS -jar app.jar $JOB_PARAMETERS
