apiVersion: v1
kind: Service
metadata:
  name: whitelist-filter
  namespace: default
  labels:
    app.kubernetes.io/name: whitelist-filter
    app.kubernetes.io/part-of: deeparcher
    app.kubernetes.io/component: whitelist-filter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: jmx
      port: 9999
      protocol: TCP
  selector:
    app.kubernetes.io/name: whitelist-filter
    app.kubernetes.io/part-of: deeparcher
    app.kubernetes.io/component: whitelist-filter