kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pdns-data-source-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdns-data-source-0
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /backup/pdns_logs
  claimRef:
    namespace: default
    name: pdns-data-source-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-gpu-node0