kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stream-whitelist-filter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client