Build graph-analyzer Kaniko Image On Branch:
  extends: .build_image_kaniko
  stage: build
  script:
    - /kaniko/default-executor --context dir://$CI_PROJECT_DIR/graph-analyzer --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE/graph-analyzer:${CI_COMMIT_BRANCH}
  except:
    - master
  only:
    - branches

Maven Build Root:
  extends: .maven_ctx
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean install
  artifacts:
    expire_in: 30 mins
    paths:
      - "*/target"

#Maven Build Graal:
#  extends: .maven_ctx
#  stage: build
#  script:
#    - mvn help:evaluate -Dexpression=project.version -q -DforceStdout > VERSION
#    - mvn $MAVEN_CLI_OPTS -DskipTests -Pgraal -DskipNativeImage package
#  artifacts:
#    paths:
#      - target/*.jar
#      - VERSION
