.maven_ctx:
  image: library/maven:3-jdk-14
  variables:
    # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
    # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
    # -DsocksProxyHost=v2ray.production -DsocksProxyPort=1080
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
    # when running from the command line.
    # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  #    HTTP_PROXY: http://v2ray.production:1081
  #    HTTPS_PROXY: http://v2ray.production:1081
  #    NO_PROXY: '*.cluster.local,*.hitnslab.com,10.0.0.0/8,172.16.0.0/12'
  before_script:
    - |
      mkdir -p .m2 .jib/base .jib/app
      cat <<-EOF > .m2/settings.xml
      <settings>
        <mirrors>
          <mirror>
            <id>aliyun-maven</id>
            <mirrorOf>central</mirrorOf>
            <name>Aliyun Mirrors</name>
            <url>https://maven.aliyun.com/repository/public</url>
          </mirror>
        </mirrors>
      </settings>
      EOF
  cache:
    paths:
      - .m2/repository/

Maven Build Root:
  extends: .maven_ctx
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean install
  artifacts:
    expire_in: 30 mins
    paths:
      - "*/target"

#Maven Build Graal:
#  extends: .maven_ctx
#  stage: build
#  script:
#    - mvn help:evaluate -Dexpression=project.version -q -DforceStdout > VERSION
#    - mvn $MAVEN_CLI_OPTS -DskipTests -Pgraal -DskipNativeImage package
#  artifacts:
#    paths:
#      - target/*.jar
#      - VERSION
