.build_image:
  stage: package
  image:
    name: gcr.azk8s.cn/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - |
      cat <<-EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
      mkdir -p $CI_PROJECT_DIR/.kaniko
      cat <<-EOF > /kaniko/default-executor
      #!/busybox/sh
      /kaniko/executor \
        --digest-file /dev/termination-log \
        --cache \
        --cache-dir $CI_PROJECT_DIR/.kaniko \
        --context dir://$CI_PROJECT_DIR \
        --build-arg HTTP_PROXY=http://v2ray:1081 \
        --build-arg HTTPS_PROXY=http://v2ray:1081 \
        "\$@"
      EOF
      chmod +x /kaniko/default-executor
    - find . -maxdepth 3
  cache:
    paths:
      - .kaniko

.build_image_on_branch:
  extends: .build_image
  script:
    - /kaniko/default-executor --dockerfile Dockerfile-CI --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - branches

.build_image_on_tag:
  extends: .build_image
  script:
    - /kaniko/default-executor --dockerfile Dockerfile-CI --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

Build Nightly Image:
  extends: .build_image_on_branch
  except:
    - master